version: "3.2"

services:
  hackney-shared-finance-test:
    image: hackney-shared-finance-test
    build:
      context: .
      dockerfile: Hackney.Shared.Finance.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}